$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'nyamy-installer.psm1') -Force

$installDir = $PSScriptRoot

# The installed files are moved to a sibling directory before they are
# deleted; install.ps1 sweeps up whatever is left there.
$installRoot = Split-Path $installDir -Parent

function Show-Usage {
    Write-Host @'
Usage: uninstall.ps1 [option]

Options:
  --help    Show this help and exit
  --force   Remove NYamy without asking for confirmation
'@
}

function Move-InstalledFilesAside([string]$Dir) {
    # Returns the directory the files were moved to, or $null if nothing moved.
    #
    # Files that are still mapped into another process - the global hook DLLs
    # stay mapped for a while after NYamy exits - cannot be deleted, but they
    # can be renamed.  Moving them out first lets the install location itself
    # disappear right away, even when deleting the files has to be retried in
    # the background.
    #
    # uninstall.* stays behind: this script is being read from that directory
    # by the shell running it, which breaks if the file moves under it.
    $items = @(
        Get-ChildItem -LiteralPath $Dir -Force |
            Where-Object { $_.Name -notmatch '^uninstall\..+$' }
    )
    if (-not $items) {
        return $null
    }

    $stash = Get-NYamyStashPath $installRoot
    New-Item -ItemType Directory -Path $stash -Force | Out-Null

    $stuck = @()
    foreach ($item in $items) {
        try {
            Move-Item -LiteralPath $item.FullName -Destination (Join-Path $stash $item.Name) -ErrorAction Stop
        }
        catch {
            # Leave it in place; the cleanup process deletes it there instead.
            $stuck += $item.Name
        }
    }

    if ($stuck) {
        Write-Host ("Could not move aside: " + ($stuck -join ', '))
        foreach ($entry in Get-NYamyBlockingProcess $Dir) {
            Write-Host "  $entry"
        }
    }
    if (-not (Get-ChildItem -LiteralPath $stash -Force)) {
        Remove-Item $stash -Force -ErrorAction SilentlyContinue
        return $null
    }
    return $stash
}

function Start-CleanupProcess([string[]]$DoomedDirs) {
    # Hand the directories to a detached PowerShell that outlives this one:
    # nothing here can delete the directory this process is still running from.
    $template = @'
# Generated by NYamy uninstall.ps1; this file deletes itself when done.
$ErrorActionPreference = 'SilentlyContinue'

# The install directory cannot go away while the uninstaller still holds it
# open, so wait that process out first.
Wait-Process -Id @PID@ -Timeout 120

$doomed = @(
@DOOMED@
)

# Keep retrying for about a minute: the shell that started the uninstaller may
# still sit in the directory, and hook DLLs are unmapped from other processes
# only as those get around to it.
for ($try = 0; $try -lt 30; $try++) {
    foreach ($dir in $doomed) {
        Remove-Item -LiteralPath $dir -Recurse -Force
    }
    if (-not ($doomed | Where-Object { Test-Path -LiteralPath $_ })) {
        break
    }
    Start-Sleep -Seconds 2
}

Remove-Item -LiteralPath $PSCommandPath -Force
'@

    $doomedLiterals = ($DoomedDirs | ForEach-Object { "    '" + $_.Replace("'", "''") + "'" }) -join "`n"
    $script = $template.Replace('@PID@', $PID).Replace('@DOOMED@', $doomedLiterals)

    $cleanupScript = Join-Path `
        $env:TEMP `
        ("NYamy-Uninstall-" + [System.Guid]::NewGuid().ToString() + ".ps1")

    # Explicit UTF-8 with BOM: install paths may hold non-ASCII characters, and
    # this is the one encoding both PowerShell hosts read a script file as.
    [System.IO.File]::WriteAllText(
        $cleanupScript, $script, (New-Object System.Text.UTF8Encoding $true))

    # Same host that is running this script, so the cleanup never depends on
    # finding a PowerShell of its own.
    $psHost = (Get-Process -Id $PID).Path
    if (-not $psHost) {
        $psHost = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    }

    Start-Process `
        -FilePath $psHost `
        -ArgumentList '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $cleanupScript `
        -WorkingDirectory $env:TEMP `
        -WindowStyle Hidden
}

#
# Argument parsing
#
$force = $false

foreach ($arg in $args) {
    if ($arg -eq '--help') {
        Show-Usage
        exit 0
    }
    elseif ($arg -eq '--force') {
        $force = $true
    }
    else {
        Write-Host "ERROR: Unknown option: $arg" -ForegroundColor Red
        Show-Usage
        exit 1
    }
}

#
# Confirmation
#
if (-not $force) {
    Write-Host "This will remove NYamy from $installDir."
    $confirmed = $null
    while ($null -eq $confirmed) {
        $answer = (Read-Host "Type 'yes' to continue, or 'no'/Enter to cancel").Trim().ToLowerInvariant()
        switch ($answer) {
            'yes' { $confirmed = $true }
            '' { $confirmed = $false }
            'no' { $confirmed = $false }
            default { Write-Host "Please answer 'yes' or 'no'." }
        }
    }
    if (-not $confirmed) {
        Write-Host "Uninstall cancelled."
        exit 0
    }
}

#
# NYamy must be gone before its files are removed.  Renaming and deleting say
# nothing about that: a running binary can be renamed just fine.
#
Assert-NYamyNotRunning $installDir 'uninstall'

Write-Host ""
Write-Host "NOTE: %LOCALAPPDATA%\NYamy will NOT be removed."
Write-Host ""

#
# Remove the Startup shortcut, if any, before scheduling self-destruction
# (this does not depend on this process exiting, unlike the directory removal below)
#
Remove-NYamyStartupShortcut $installDir

#
# Get the files out of the way, then have a detached process delete both what
# was moved aside and the install directory itself once this one is gone
#
# A directory cannot be renamed or removed while any process has it as its
# current directory, this one included.  uninstall.cmd already steps out of it,
# but the script may be started by other means.  Set-Location would not do:
# it leaves the process-wide current directory, which is what Windows holds,
# untouched.
#
if ([Environment]::CurrentDirectory.TrimEnd('\').StartsWith(
        $installDir.TrimEnd('\'), [System.StringComparison]::OrdinalIgnoreCase)) {
    [Environment]::CurrentDirectory = $env:TEMP
}

Write-NYamyPhase "Removing $installDir..."
$stashDir = Move-InstalledFilesAside $installDir

$doomedDirs = @($installDir)
if ($stashDir) {
    $doomedDirs += $stashDir
}

Start-CleanupProcess $doomedDirs

Write-NYamyPhase "Uninstall scheduled: $installDir"
Write-Host "The installation directory will be removed after this process exits."
if ($stashDir) {
    Write-Host "Files a running process still holds are retried for a minute in"
    Write-Host "$stashDir; whatever survives that is harmless,"
    Write-Host "and installing NYamy again removes it."
}

exit 0
