param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$InputPath,
    
    [Parameter(Mandatory = $true, Position = 1)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

# Open Input File
if (-not (Test-Path $InputPath)) {
    Write-Error "can't open $InputPath"
    exit 1
}

$content = Get-Content -Path $InputPath -Raw
# CRLF handling might vary, Get-Content -Raw preserves it mostly but let's normalize splitting.
# JS used ReadLine() loop.

$lines = $content -split "`r`n|`n"

$extract = $false
$buffer = ""

foreach ($line in $lines) {
    if ($line -match "BEGINING OF FUNCTION DEFINITION") {
        $extract = $true
        continue
    }
    if ($extract) {
        if ($line -match "END OF FUNCTION DEFINITION") {
            break
        }
        # JS: if (buf.match("///") == null) line += buf;
        if (-not ($line -match "///")) {
            $buffer += $line
        }
    }
}

# JS: line = line.replace(/\s+/g, " ");
$buffer = $buffer -replace "\s+", " "

$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine("// DO NOT EDIT")
$null = $sb.AppendLine("// this file is automatically generated by makefunc")
$null = $sb.AppendLine("// see dependency information in mayu-common.mak")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("#ifdef FUNCTION_DATA")

# JS: var lines = line.split(";");
$statements = $buffer -split ";"
$names = @()

foreach ($stmt in $statements) {
    # JS: /^\s*\w+\s+func(\w+)\s*\(\s*FunctionParam\s*\*\s*\w+\s*,?\s*(.*?)\s*\)\s*$/
    if ($stmt -match "^\s*\w+\s+func(\w+)\s*\(\s*FunctionParam\s*\*\s*\w+\s*,?\s*(.*?)\s*\)\s*$") {
        # $matches[0] is full match
        # $matches[1] is name (Group 1)
        # $matches[2] is args (Group 2)
        
        $name = $matches[1]
        $names += $name
        $argStr = $matches[2]
        
        $null = $sb.AppendLine("class FunctionData_$name : public FunctionData")
        $null = $sb.AppendLine("{")
        $null = $sb.AppendLine("public:")
        
        # JS: var args = entry[2].split(/\s*,\s*/);
        # Careful with empty args
        $argList = @()
        if (-not [string]::IsNullOrWhiteSpace($argStr)) {
            $argList = $argStr -split "\s*,\s*"
        }
        
        $cleanArgs = @()
        # Parse args first to gather info
        foreach ($argRaw in $argList) {
            $arg = $argRaw.Trim()
            if ($arg -eq "") { continue }
            
            $defaultValue = ""
            $type = ""
            $argName = ""
            $isReference = $false
            
            # JS: if (arg.match(/^(.*\S)\s*=\s*(\S.*)$/))
            if ($arg -match "^(.*\S)\s*=\s*(\S.*)$") {
                $arg = $matches[1]
                $defaultValue = $matches[2]
            }
            
            # JS: if (arg.match(/^(.*\S\s*\*)\s*i_(\w+)$/))
            if ($arg -match "^(.*\S\s*\*)\s*i_(\w+)$") {
                $type = $matches[1]
                $argName = $matches[2]
            } 
            # JS: else if (arg.match(/^const\s*(.*\S)\s*&\s*i_(\w+)$/))
            elseif ($arg -match "^const\s*(.*\S)\s*&\s*i_(\w+)$") {
                $type = $matches[1]
                $argName = $matches[2]
                $isReference = $true
            }
            # JS: else if (arg.match(/^(.*\S)\s*i_(\w+)$/))
            elseif ($arg -match "^(.*\S)\s*i_(\w+)$") {
                $type = $matches[1]
                $argName = $matches[2]
            }
            else {
                Write-Error "parse error! arg: $arg"
                exit 1
            }
            
            $cleanArgs += [PSCustomObject]@{
                Type         = $type
                ArgName      = $argName
                DefaultValue = $defaultValue
                IsReference  = $isReference
            }
        }
        
        $argc = $cleanArgs.Count
        
        # Member declaration
        foreach ($a in $cleanArgs) {
            $null = $sb.AppendLine("  $($a.Type) m_$($a.ArgName);")
        }
        
        $null = $sb.AppendLine("")
        $null = $sb.AppendLine("public:")
        $null = $sb.AppendLine("  static FunctionData *create()")
        $null = $sb.AppendLine("  {")
        $null = $sb.AppendLine("    FunctionData_$name *fd")
        $null = $sb.AppendLine("      = new FunctionData_$name;")
        
        foreach ($a in $cleanArgs) {
            if ($a.DefaultValue) {
                $null = $sb.AppendLine("    fd->m_$($a.ArgName) = $($a.DefaultValue);")
            }
        }
        
        $null = $sb.AppendLine("    return fd;")
        $null = $sb.AppendLine("  }")
        $null = $sb.AppendLine("  ")
        
        # Load function
        $null = $sb.AppendLine("  virtual void load(SettingLoader *i_sl)")
        $null = $sb.AppendLine("  {")
        
        if ($argc -eq 0 -or $cleanArgs[0].DefaultValue) {
            $null = $sb.AppendLine("    if (!i_sl->getOpenParen(false, FunctionData_${name}::getName()))")
            $null = $sb.AppendLine("      return;")
        }
        else {
            $null = $sb.AppendLine("    i_sl->getOpenParen(true, FunctionData_${name}::getName()); // throw ...")
        }
        
        for ($i = 0; $i -lt $argc; $i++) {
            $a = $cleanArgs[$i]
            
            if ($a.DefaultValue) {
                $null = $sb.AppendLine("    if (i_sl->getCloseParen(false, FunctionData_${name}::getName()))")
                $null = $sb.AppendLine("      return;")
            }
            if ($i -gt 0) {
                $null = $sb.AppendLine("    i_sl->getComma(false, FunctionData_${name}::getName()); // throw ...")
            }
            $null = $sb.AppendLine("    i_sl->load_ARGUMENT(&m_$($a.ArgName));")
        }
        
        $null = $sb.AppendLine("    i_sl->getCloseParen(true, FunctionData_${name}::getName()); // throw ...")
        $null = $sb.AppendLine("  }")
        $null = $sb.AppendLine("")
        
        # Exec function
        $null = $sb.AppendLine("  virtual void exec(Engine *i_engine, FunctionParam *i_param) const")
        $null = $sb.AppendLine("  {")
        
        $callArgs = "i_param"
        foreach ($a in $cleanArgs) {
            $callArgs += ", m_$($a.ArgName)"
        }
        $null = $sb.AppendLine("    i_engine->func$name($callArgs);")
        
        $null = $sb.AppendLine("  }")
        $null = $sb.AppendLine("")
        
        # GetName
        $null = $sb.AppendLine("  inline virtual const _TCHAR *getName() const")
        $null = $sb.AppendLine("  {")
        $null = $sb.AppendLine("    return _T(`"$name`");")
        $null = $sb.AppendLine("  }")
        $null = $sb.AppendLine("")
        
        # Output
        $null = $sb.AppendLine("  virtual tostream &output(tostream &i_ost) const")
        $null = $sb.AppendLine("  {")
        $null = $sb.AppendLine("    i_ost << _T(`"&`") << getName();")
        
        if ($argc -gt 0) {
            $null = $sb.AppendLine("    i_ost << _T(`"(`");")
        }
        
        for ($i = 0; $i -lt $argc; $i++) {
            $a = $cleanArgs[$i]
            if ($i -eq $argc - 1) {
                # Last arg
                $null = $sb.AppendLine("    i_ost << m_$($a.ArgName);")
            }
            else {
                $null = $sb.AppendLine("    i_ost << m_$($a.ArgName) << _T(`", `");")
            }
        }
        
        if ($argc -gt 0) {
            $null = $sb.AppendLine("    i_ost << _T(`") `");")
        }
        $null = $sb.AppendLine("    return i_ost;")
        $null = $sb.AppendLine("  }")
        $null = $sb.AppendLine("")
        
        # Clone
        $null = $sb.AppendLine("  virtual FunctionData *clone() const")
        $null = $sb.AppendLine("  {")
        $null = $sb.AppendLine("    return new FunctionData_$name(*this);")
        $null = $sb.AppendLine("  }")
        
        $null = $sb.AppendLine("};")
        $null = $sb.AppendLine("")
    }
}

$null = $sb.AppendLine("#endif // FUNCTION_DATA")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("#ifdef FUNCTION_FRIEND")

foreach ($name in $names) {
    $null = $sb.AppendLine("friend class FunctionData_$name;")
}

$null = $sb.AppendLine("#endif // FUNCTION_FRIEND")
$null = $sb.AppendLine("")
$null = $sb.AppendLine("#ifdef FUNCTION_CREATOR")
$null = $sb.AppendLine("FunctionCreator functionCreators[] = {")

foreach ($name in $names) {
    $null = $sb.AppendLine("  { _T(`"$name`"), FunctionData_${name}::create },")
}

$null = $sb.AppendLine("};")
$null = $sb.AppendLine("#endif // FUNCTION_CREATOR")

# Write to file (UTF8 with BOM or just UTF8?)
# JS fso.CreateTextFile defaults to ASCII? Or system default. 
# Usually source files are ASCII or UTF8. 
# Let's use UTF8.
$sb.ToString() | Out-File -FilePath $OutputPath -Encoding utf8
